movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('recommended/<int:genre_pk>', views.recommended, name='recommended'),
]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

movies/models.py
from django.db import models

class Genre(models.Model):
    name = models.CharField(max_length=50)

class Movie(models.Model):
    title = models.CharField(max_length=100)
    release_date = models.DateField()
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    overview = models.TextField()
    poster_path = models.CharField(max_length=200)
    genres = models.ManyToManyField(Genre)

movies/forms.py
from django import forms

# Create your forms here.

movies/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_safe
from django.contrib.auth.decorators import login_required
from .models import Genre, Movie
from django.http import JsonResponse

# Create your views here.
@require_safe
def index(request):
    movies = Movie.objects.all()
    genres = Genre.objects.all()

    context = {
        'movies': movies,
        'genres': genres,
    }

    return render(request, 'movies/index.html', context)


@require_safe
def detail(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    context = {
        'movie':movie,
    }
    return render(request, 'movies/detail.html', context)


@require_safe
def recommended(request, genre_pk):
    movies = Movie.objects.all()
    genres = Genre.objects.all()

    movie_lst = []
    for movie in movies:
        m = movie.genres.values()
        # print(m)
        # lst.append(movie.title)
        # lst.append(movie.vote_average)
        for i in m:
            if i['id'] == genre_pk:
                movie_lst .append(movie)


    #     movie_lst.append(lst)
    # # print(movie_lst)
    # movielst = []
    # for mo in movie_lst:
    #     if genre_pk in mo:
    #         movielst.append(m[0])
    # movielst.sort(key=lambda x:x[1], reverse=True)



    context = {
        'movies': movies,
        'genres': genres,
        'genre_pk':genre_pk, 
        'movie_lst':movie_lst,
        
    }
    return render(request, 'movies/recommended.html', context)

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
  <img src="{{movie.poster_path}}" alt="" style="width: 200px; height: 300px;">
  <p>영화제목: {{movie.title}}</p>
  <p>
    장르:
    {% for genre in movie.genres.all %}
      {{ genre.name }}
    {% endfor %}
  </p>
  <p>평점: {{movie.vote_average}}</p>
  <p>평점을 매긴 사람: {{movie.vote_count}}</p>
  <p>개봉일: {{movie.release_date}}</p>
  <p>줄거리: {{movie.overview}}</p>
  
  <br>
  <hr>
  <a href="{% url 'movies:index' %}">Back</a>
{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Movies</h1>

      
  <!-- 카드 예시 -->
  
    <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for movie in movies %}
      <div class="col">
        <div class="card h-100">
          <img src="{{movie.poster_path}}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">
              <a style="text-decoration:none" class="fw-bold text-secondary" href="{% url 'movies:detail' movie.pk %}">
                영화제목: {{movie.title}}
              </a></h5>
            <p class="card-text">
              평점: {{movie.vote_average}}
              <h4>
                장르:
                {% for genre in movie.genres.all %}
                  {{ genre.name }}
                {% endfor %}
              </h4>
            </p>
          </div>
        </div>
      </div>
  {% endfor %}
</div>
  
{% endblock %}

movies/templates/movies/recommended.html
{% extends 'base.html' %}

{% block content %}
  <h1>추천영화</h1>
  <h1>{{ genre_pk }}</h1>
  <h3>장르별 추천 영화</h3>
  {% for genre in genres %}
  <button id="genre_search-{{genre.pk}}" class="m-1">
      <a href="{{genre.pk}}">{{genre.name}}</a>
  </button>
  {% endfor %}
<div>
  {% for m in movie_lst %}
    <p><a href="{% url 'movies:detail'  m.pk %}">{{ m.title }}</a></p>
    <hr>
  {% endfor %}

  
</div>
  

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
  const 
  const adventure = document.querySelector('#genre_search-${}')
</script> 
{% endblock %}