accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/comments/create/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/like/', views.like, name='like'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('recommended/<int:genre_pk>', views.recommended, name='recommended'),
]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <title>Document</title>
</head>
<body class="">
  <div class="container">
    <nav class="bg-black text-white">
      {% if user.is_authenticated %}
      <h3 class="m-4 p-4">Hello, {{ user.username }}</h3>
      <a class="text-white m-4" href="{% url 'accounts:profile' user %}" style="text-decoration:none">내 프로필</a>
      <form action="{% url 'accounts:logout' %}" method="POST">
        {% csrf_token %}
        <input class="btn btn-primary m-4" type="submit" value="Logout">
      </form>
      <div style="text-decoration:none"> 
        <a class="text-white m-4 " href="{% url 'movies:index'%}" style="text-decoration:none">Movie</a>
        <a class="text-white m-4" href="{% url 'community:index'%}" style="text-decoration:none">Community</a>
        <a class="text-white m-4" href="{% url 'community:create'%}" style="text-decoration:none">New Review</a>
        <a class="text-white m-4" href="{% url 'movies:recommended' 0 %}" style="text-decoration:none">Recommended Movie</a>
        <br>
        {% else %}
        <a href="{% url 'accounts:signup' %}">Signup</a>
        <a href="{% url 'accounts:login' %}">Login</a>
        {% endif %} 
        <br>
      </div>
    </nav>
    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>